# PHP

trigger:
  branches:
    include:
      - trunk
  paths:
    exclude:
      - azure-pipelines.yml
pr:
  branches:
    include:
      - trunk
      - release-v*
      - hotfix-v*
pool:
    vmImage: ubuntu-latest
variables:
    phpVersion: 8.2
    npm_config_cache: $(Pipeline.Workspace)/.npm
    COMPOSER_CACHE_DIR: $(Pipeline.Workspace)/.composer

steps:
  - script: |
      sudo update-alternatives --set php /usr/bin/php$(phpVersion)
      sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
      php -version
    displayName: 'Use PHP version $(phpVersion)'
  - task: Cache@2
    inputs:
      key: 'composer | "$(Agent.OS)" | composer.lock'
      restoreKeys: |
        composer | "$(Agent.OS)"
        composer
      path: $(COMPOSER_CACHE_DIR)
    displayName: Cache composer
  - script: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
    displayName: 'composer install'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '24.x'
  - script: npm install -g npm@11.16.0
    displayName: 'Force functinal NPM version'
  - script: |
      node --version
      npm --version
    displayName: 'Check Node/npm versions'
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)
    displayName: Cache npm
  - task: Npm@1
    inputs:
      command: 'ci'
    displayName: NPM Clean Install
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'
    displayName: NPM Build
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'prune --omit=dev'
    displayName: NPM Prune Dev Deps
  - task: replacetokens@6
    inputs:
      sources: 'style.css'
      addBOM: true
  - task: DeleteFiles@1
    inputs:
      SourceFolder:
      Contents: |
        /vrt
        /reports
        /.git
        /.git*
      RemoveDotFiles: true
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: 'bc-sitka-spruce-department-theme'
      publishLocation: 'pipeline'
