const wysiwygBlocks = [
	'mayflower-blocks/button',
	'mayflower-blocks/card',
	//'mayflower-blocks/collapse',
	'mayflower-blocks/collapsibles',
	'mayflower-blocks/row',
	//'mayflower-blocks/column',
	'mayflower-blocks/tabs', // likely should be replaced by tabcordion
	'core/group',
	'core/heading',
	'core/paragraph',
	'core/image',
	'core/list',
	'core/quote',
	'core/embed',
	'gravityforms/form',
	'tablepress/table',
	'mayflower-blocks/alert',
	'mayflower-blocks/course',
	'mayflower-blocks/lead',
	'core/cover',
	'core/file',
	'core/gallery',
	'core/media-text',
	'core/separator',
	'core/shortcode',
	'core/spacer',
];

export { wysiwygBlocks };
